version: '3.3'
services:
  app:
    build: .
    command: 'npm start'
    ports:
      - '4200:4200'
      - '49153:49153'
    expose:
      - '4200'
      - '49153'
    volumes:
      - './pickAngular/:/usr/app/'
  api:
    build: .
    command: 'npm start'
    ports:
      - '3000:3000'
    volumes:
      - './api/:/usr/app/api'